apiVersion: apps/v1
kind: Deployment
metadata:
  name: otterweb-deployment
  namespace: {{ .Values.resource.namespace | default .Values.resource.minikube_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otterweb
  template:
    metadata:
      labels:
        app: otterweb
    spec:
      containers:      
        - name: otterweb
          image: {{ .Values.otterImage.repository }}:{{ .Values.otterImage.tag }} 
          imagePullPolicy: {{ .Values.otterImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.otterImage.port }}
          env:
            - name: ARANGO_URL
              value: http://{{ .Values.env.arango_url }}:{{ .Values.arangoImage.port }}
            - name: "OTTERDB_PASS"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password

            - name: "OTTER_WEB_BASE_URL"
              value: {{ .Values.env.web_base_url }}