apiVersion: apps/v1
kind: Deployment
metadata:
  name: otterweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otterweb
  template:
    metadata:
      labels:
        app: otterweb
    spec:
      containers:
        - name: otterweb
          image: {{ .Values.otterImage.repository }}:{{ .Values.otterImage.tag }} 
          imagePullPolicy: {{ .Values.otterImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.otterImage.port }}
          env:
            - name: ARANGO_URL
              value: {{ .Values.env.arango_url }}
            - name: "OTTERDB_PASS"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password