apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otterdb-deployment
  namespace: {{ .Values.resource.namespace | default .Values.resource.minikube_namespace }}
spec:
  serviceName: otterdb
  replicas: 1
  selector:
    matchLabels:
      app: otterdb
  template:
    metadata:
      labels:
        app: otterdb
    spec:
      volumes:
        - name: otterdb-storage
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvcName }}
      containers:      
        - name: otterdb
          image: {{ .Values.arangoImage.repository }}:{{ .Values.arangoImage.tag }} 
          imagePullPolicy: {{ .Values.arangoImage.pullPolicy }}
          {{- if .Values.arangoImage.securityContext }}
          securityContext:
            {{- toYaml .Values.arangoImage.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.arangoImage.resources }}
          resources:
            {{- toYaml .Values.arangoImage.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.arangoImage.port }}
          volumeMounts:
            - name: {{ .Values.storage.name }}
              mountPath: {{ .Values.storage.path }}
          env:
            - name: DB_LINK_PORT_8529_TCP
              value: http://{{ .Values.env.arango_url }}:{{ .Values.arangoImage.port }}
            - name: "ARANGO_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user
            - name: "ARANGO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password
            - name: "ARANGO_USER_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: average_user
            - name: "ARANGO_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: average_user_password
            - name: "OTTERDB_PASS"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password
