apiVersion: v1
kind: Service
metadata:
  name: otter-service
spec:
  type: {{ .Values.service.dbtype }}
  selector:
    app: otter
  ports:
    - name: otter
      port: {{ .Values.arangoImage.port }}
      targetPort: {{ .Values.arangoImage.port }}
      protocol: TCP