apiVersion: v1
kind: Service
metadata:
  name: otterdb-service
  namespace: {{ .Values.resource.namespace | default .Values.resource.minikube_namespace }}
spec:
  type: {{ .Values.service.dbtype }}
  selector:
    app: otterdb
  ports:
    - name: otterdb
      port: {{ .Values.arangoImage.port }}
      targetPort: {{ .Values.arangoImage.port }}
      protocol: TCP