apiVersion: v1
kind: Service
metadata:
  name: otterweb-service
  namespace: {{ .Values.resource.namespace | default .Values.resource.minikube_namespace }}
spec:
  type: {{ .Values.service.webtype }}
  selector:
    app: otterweb
  ports:
    - name: otterweb
      port: {{ .Values.otterImage.port }}
      targetPort: {{ .Values.otterImage.port }}
      protocol: TCP