apiVersion: apps/v1
kind: Deployment
metadata:
  name: otter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otter
  template:
    metadata:
      labels:
        app: otter
    spec:
      containers:
      
        - name: otterdb
          image: {{ .Values.arangoImage.repository }}:{{ .Values.arangoImage.tag }} 
          imagePullPolicy: {{ .Values.arangoImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.arangoImage.port }}
          env:
            - name: DB_LINK_PORT_8529_TCP
              value: {{ .Values.env.arango_url }}
            - name: "ARANGO_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user
            - name: "ARANGO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password
            - name: "ARANGO_USER_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: average_user
            - name: "ARANGO_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: average_user_password
            - name: "OTTERDB_PASS"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password

        - name: otterweb
          image: {{ .Values.otterImage.repository }}:{{ .Values.otterImage.tag }} 
          imagePullPolicy: {{ .Values.otterImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.otterImage.port }}
          env:
            - name: ARANGO_URL
              value: {{ .Values.env.arango_url }}
            - name: "OTTERDB_PASS"
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: root_user_password