apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otterdb-pv-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}