apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otterdb-pv-claim
  namespace: {{ .Values.resource.namespace | default .Values.resource.minikube_namespace }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}