# file: secrets.yaml
# copy this file to "secrets.yaml" and edit the passwords
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  root_user: {{ .Values.secret.root_user | b64enc }}
  root_user_password:  {{ .Values.secret.root_user_password | b64enc }}
  average_user:  {{ .Values.secret.average_user | b64enc }}
  average_user_password:  {{ .Values.secret.average_user_password | b64enc }}

