apiVersion: v1
kind: Service
metadata:
  name: otter-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: otterweb-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.otterImage.port }}
      protocol: TCP
    - name: otterdb-port
      port: {{ .Values.arangoImage.port }}
      targetPort: {{ .Values.arangoImage.port }}
      protocol: TCP
     